import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import Image from "next/image";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <div className="bg-blue-800 p-6">
          <nav>
            <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
              <Link href="#" className="flex items-center space-x-3 rtl:space-x-reverse">
                  <Image
                    src="/strat_logo.png"
                    alt="Globe icon"
                    width={155}
                    height={50}
                  />
                  <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white"></span>
              </Link>
              <div className="hidden w-full md:block md:w-auto" id="navbar-default">
                <ul className="font-medium flex flex-col p-4 md:p-0 mt-4 border md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0">
                  <li>
                    <Link href="/" className="block py-2 px-3 font-bold text-white bg-black-700 rounded-sm md:bg-transparent md:text-white-700 md:p-0 md:hover:text-gray-300 dark:text-white md:dark:text-blue-500" aria-current="page">Home</Link>
                  </li>
                  <li>
                    <Link href="/pages/project" className="block py-2 px-3 text-white rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-gray-300 md:p-0 dark:text-white md:dark:hover:text-gray-300 dark:hover:bg-gray-500 dark:hover:text-white md:dark:hover:bg-transparent">Projects</Link>
                  </li>
                  <li>
                    <Link href="/pages/aboutMe" className="block py-2 px-3 text-white rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-gray-300 md:p-0 dark:text-white md:dark:hover:text-gray-300 dark:hover:bg-gray-500 dark:hover:text-white md:dark:hover:bg-transparent">About Me</Link>
                  </li>
                  <li>
                    <Link href="/pages/contact" className="block py-2 px-3 text-white rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-gray-300 md:p-0 dark:text-white md:dark:hover:text-gray-300 dark:hover:bg-gray-500 dark:hover:text-white md:dark:hover:bg-transparent">Contract</Link>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </div>
        {children}
      </body>
    </html>
    <footer className="bg-blue-700 text-white text-center py-8">
        <div>
          <p>Portfolio Made by Rod Feliser P. Torre</p>
          <p>Email: i_rodfeliser.torre@stratpoint.com</p>
        </div>
      </footer>
      </div>
  );
}
